name: Build-Stockfish-Ultra

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang lld ninja-build cmake zip python3 build-essential

    # Clone Stockfish source into engines/stockfish_src
    - name: Clone Stockfish source @ ce73441f
      run: |
        git clone https://github.com/official-stockfish/Stockfish.git engines/stockfish_src
        cd engines/stockfish_src
        git checkout ce73441f2013e0b8fd3eb7a0c9fd391d52adde70

    # Build Stockfish directly without profile-build
    - name: Build Stockfish (no profile-build)
      run: |
        cd engines/stockfish_src
        make -j$(nproc) ARCH=x86-64-bmi2 LTO=1 COMP=clang

    # Optimize with PGO and Thin-LTO
    - name: Optimized PGO + ThinLTO build
      run: |
        cd engines/stockfish_src
        make -j$(nproc) ARCH=x86-64-bmi2 LTO=1 COMP=clang \
             EXTRA_CXXFLAGS="-flto=thin -fipa-pta"
        strip stockfish

    # Zip the binary for release
    - name: Zip ultra binary
      run: |
        cd engines/stockfish_src
        zip ../../stockfish_bmi2_ultra.zip stockfish

    # Upload the compiled Stockfish as an artifact
    - name: Upload compiled Stockfish
      uses: actions/upload-artifact@v4
      with:
        name: stockfish-bmi2-ultra
        path: stockfish_bmi2_ultra.zip
